package ru.capjack.tool.csi.core

enum class ConnectionCloseReason(val flag: Byte) {
	CLOSE(ProtocolFlag.CLOSE),
	SERVER_SHUTDOWN(ProtocolFlag.CLOSE_SERVER_SHUTDOWN),
	ACTIVITY_TIMEOUT_EXPIRED(ProtocolFlag.CLOSE_ACTIVITY_TIMEOUT_EXPIRED),
	AUTHORIZATION_REJECT(ProtocolFlag.CLOSE_AUTHORIZATION_REJECT),
	RECOVERY_REJECT(ProtocolFlag.CLOSE_RECOVERY_REJECT),
	CONCURRENT(ProtocolFlag.CLOSE_CONCURRENT),
	PROTOCOL_BROKEN(ProtocolFlag.CLOSE_PROTOCOL_BROKEN),
	SERVER_ERROR(ProtocolFlag.CLOSE_SERVER_ERROR)
}